### ISSUE TITLE
Password doesn't work

### ISSUE THREAD

**Issue by imkunalbhansali** [samokosik/COMB#1]
Hello, just downloaded the archive. I tried unzipping the archive using the password (+w/P3PRqQQoJ6g). Unfortunately this didn't work. Please look into this and update the password

**Comment by samokosik** [comment]
Interesting, no one reported this issue before...
I will be creating a new zip file that does not contain a password protection. By the time, may you, please, tell me what program did you use to unzip it?

**Comment by imkunalbhansali** [comment]
I used MAC's default inbuilt system to unzip the file.

**Comment by samokosik** [comment]
Ight, may you try it with unzip (brew install unzip) and post the output?

**Comment by imkunalbhansali** [comment]
Hello, looks like the issue is with Mac's inbuilt tool. I just tried it with brew install p7zip and it works! Thanks
