### ISSUE TITLE
How do I use it ?

### ISSUE THREAD

**Issue by daarkstrnght** [samokosik/COMB#4]
This technically isn't an issue, but I'd like to know how do I use the archives contained in this zip, I downloaded, extracted and now I don't now what to do with them.
Do I have to download a specific software to open or do something else ? 

Thanks.

**Comment by samokosik** [comment]
Hey, it can be used with programs such as breach parse: https://github.com/hmaverickadams/breach-parse
Add the second part of the mail (@gmail.com) and you will get breached passwords for that domain.

Or it can be used for password spraying attacks.
