### ISSUE TITLE
Won't download

### ISSUE THREAD

**Issue by stuxnet8t8** [samokosik/COMB#8]
Tried downloading the archive from your onedrive probably 10 times now,  will not complete. I understand the compressed file is 18-ish GB? Closest I've got is 17.3gb downloaded, wouldn't extract, said it was empty, basically. Can't really be bothered messing with torrents if I don't have to.. 

Any ideas?

**Comment by samokosik** [comment]
Compressed file was far closer to 40 gb. The one on onedrive is not compressed and should be around 99 gigs...
Once you got thosw 17.3 gb, may I ask how the structure looked? Were there all files for a-z/1-9?

**Comment by stuxnet8t8** [comment]
> Compressed file was far closer to 40 gb. The one on onedrive is not compressed and should be around 99 gigs...
> Once you got thosw 17.3 gb, may I ask how the structure looked? Were there all files for a-z/1-9?

Maybe my terminology is off, I apologise I'm tired lol. The .ZIP file is 18.6gb, yes? I've got it downloading on qbitorrent now, it's pulling a 18.6gb file, didn't realise the onedrive was uncompressed lol, anyway, I'll let you know if the torrent works and I'll close the issue. Thanks for the prompt reply. 

As for the structure, it wouldn't let me view it, extract it or interact with it in anyway, however it saved it and when I cat'd the file it basically started pulling alphabetically listed email/pw pairs until I ctrl+c'd it. Which tells me the files existed somewhere.  I ran the zip through one of those websites where you can view the contents and everything was there except for the last few files which had errors attached. Idk if it was a internet speed/connection issue, no idea.

**Comment by samokosik** [comment]
Alright, keep me informed ;)

**Comment by stuxnet8t8** [comment]
Got it downloaded, haven't tried to unzip it yet but I have the file on my device, torrent worked perfectly, Thanks again.
